### ISSUE TITLE
change 's. d.' to 's.d.' in french reference style

### ISSUE THREAD

**Issue by ElsLommelen** [inbo/styles#2]
Similarly to the Dutch and English style, I would propose to also omit the space in the French style for reports of the research institute for nature and forest.

**Comment by ElsLommelen** [comment]
I'm afraid I did something wrong: I cloned the repo locally, made a branch, pushed a commit and made a PR.  After that, I noticed the PR was made in the main repo on citation-style-language and not in this fork.  How can I solve this mistake?  Or is this just the way it works?

**Comment by florisvdh** [comment]
It's because the target of a fork's PR is the upstream repo by default. The easiest for now is to turn it into a draft PR (which I cannot), then I can add a few more changes (next week or so) to include in a new release. The upside of a draft PR to the upstream repo is that some automated checks are run already. The alternative is to change the target repo of the PR to the current repo, which you can also do I think, at the top of the PR page, so that we can finish the PR in this repo before switching target repo to upstream again.

**Comment by florisvdh** [comment]
@ElsLommelen your implementation of the `s. d.` to `s.d.` overruling in #5634 looks fine indeed. :+1:

In an effort to make a next release of the INBO CSL style file (long overdue task), I was looking whether other things needed to be changed here, for French.

@cecileherr @ElsLommelen You probably already checked the citation & bibliographic output in French, see clickable details at the end of this post? These are the bibliographic data from https://inbo.github.io/inbomd_examples/citation_style/en/index.html (where English is rendered).

I was surprised that the CSL term `in` is [rendered in fr-FR as 'in'](https://github.com/citation-style-language/locales/blob/d5ee85de8e74d4109509014758b6f496a968ff03/locales-fr-FR.xml#L42) and not as 'dans', but it appears it must be regarded as the Latin _in,_ as discussed in https://github.com/citation-style-language/locales/pull/23 and https://forums.zotero.org/discussion/4738/4/#Item_29. However [in fr-CA](https://github.com/citation-style-language/locales/blob/d5ee85de8e74d4109509014758b6f496a968ff03/locales-fr-CA.xml#L42) it is translated to 'dans' nonetheless.

Regarding the space between `s.` and `d.`, it might be argued that it should be removed in the above referred (central) CSL locale files. The presence or absence of a space for the _short_ form of the `no date` term seems to vary according to language, which looks like an inconsistency, but perhaps abbreviation 'defaults' (spacing/no spacing in abbreviations) do differ between languages and countries. @cecileherr if you're convinced it's better to remove this space (and perhaps also for other terms) in the CSL source, feel free to make an issue at https://github.com/citation-style-language/locales. The role of CSL locale files is explained in https://docs.citationstyles.org/en/stable/specification.html#locale and https://docs.citationstyles.org/en/stable/specification.html#locale-files-structure. Changing it there, if appropriate, would 'solve' this for any CSL style when a style is used for rendering French.

<details><summary><strong><i>citations & bibliography</i></strong></summary>

**Individual Citations**
(Wikipedia, 2019)
(Oosterlynck, 2019)
(Onkelinx et al., 2019)
(Lastname, 2020)
(European Topic Centre on Biological Diversity ETC/BD, 2016)
(Databank Ondergrond Vlaanderen, s.d.)
(áâàäçéêëèíuîïìóôöòúûüù, 2020)
(Achternaam, 2020b)
(Achternaam, 2020f)
(Achternaam, 2020d)
(Achternaam, 2020g)
(Van de Achternaam, 2020)
(De Achternaam, 2020)
(Achternaam, 2020e)
(Misc, 2020)
(Achternaam, 2020c)
(Achternaam, 2020a)
(Unpublished et al., 2020)
(Unpublished & Second, 2020)
(Unpublished, 2020)
(TechnicalReport et al., 2020)
(TechnicalReport & Second, 2020)
(TechnicalReport, 2020)
(PhDThesis, 2020)
(MasterThesis, 2020)
(Manual et al., 2020)
(Manual & Second, 2020)
(Proceedings et al., 2020)
(Manual, 2020)
(Anonymous, 2020a)
(Proceedings & Second, 2020)
(Proceedings, 2020)
(Anonymous, 2020b)
(ProceedingsAuthor et al., 2020)
(ProceedingsAuthor & Second, 2020)
(ProceedingsAuthor, 2020)
(Conference et al., 2020)
(Conference & Second, 2020)
(Conference, 2020)
(InCollection et al., 2020)
(InCollection & Second, 2020)
(InCollection, 2020)
(Booklet et al., 2020)
(Booklet & Second, 2020)
(Anonymous, 2020c)
(Chapter, 2020c)
(Chapter et al., 2020)
(Chapter & Second, 2020)
(Booklet, 2020)
(Chapter, 2020a)
(Chapter, 2020b)
(Book et al., 2020b)
(Book & Second, 2020b)
(Book et al., 2020a)
(Book & Second, 2020a)
(Book, 2020b)
(Book, 2020a)
(Article et al., 2020)
(Zuur et al., 2009)
(Yli-Viikari et al., 2007)
(Article & Second, 2020)
(Article, 2020)
(Wickham, 2007)
(Vander Mijnsbrugge & Onkelinx, 2005)
(R Core Team, 2013)
(Onkelinx et al., 2014b)
(Onkelinx et al., 2014a)
(Onkelinx et al., 2012)
(Onkelinx, 2009)
(Laferrière & Stoett, 1999)
(Kish, 1965)
(Franklin, 2009)
(Diggle & Ribeiro, 2007)
(Degraer et al., 2013)
(Bolker, 2008)
(Banerjee et al., 2003)
(Anselin et al., 2014)
(Amano, 2012)
(Agresti, 2002)

**Single Citation (with position "first")**
(áâàäçéêëèíuîïìóôöòúûüù, 2020; Achternaam, 2020a, 2020b, 2020c, 2020d, 2020e, 2020f, 2020g; Agresti, 2002; Amano, 2012; Anonymous, 2020a, 2020b, 2020c; Anselin et al., 2014; Article, 2020; Article et al., 2020; Article & Second, 2020; Banerjee et al., 2003; Bolker, 2008; Book, 2020a, 2020b; Book et al., 2020a, 2020b; Book & Second, 2020a, 2020b; Booklet, 2020; Booklet et al., 2020; Booklet & Second, 2020; Chapter, 2020a, 2020b, 2020c; Chapter et al., 2020; Chapter & Second, 2020; Conference, 2020; Conference et al., 2020; Conference & Second, 2020; Databank Ondergrond Vlaanderen, s.d.; De Achternaam, 2020; Degraer et al., 2013; Diggle & Ribeiro, 2007; European Topic Centre on Biological Diversity ETC/BD, 2016; Franklin, 2009; InCollection, 2020; InCollection et al., 2020; InCollection & Second, 2020; Kish, 1965; Laferrière & Stoett, 1999; Lastname, 2020; Manual, 2020; Manual et al., 2020; Manual & Second, 2020; MasterThesis, 2020; Misc, 2020; Onkelinx, 2009; Onkelinx et al., 2012, 2014b, 2014a, 2019; Oosterlynck, 2019; PhDThesis, 2020; Proceedings, 2020; Proceedings et al., 2020; Proceedings & Second, 2020; ProceedingsAuthor, 2020; ProceedingsAuthor et al., 2020; ProceedingsAuthor & Second, 2020; R Core Team, 2013; TechnicalReport, 2020; TechnicalReport et al., 2020; TechnicalReport & Second, 2020; Unpublished, 2020; Unpublished et al., 2020; Unpublished & Second, 2020; Van de Achternaam, 2020; Vander Mijnsbrugge & Onkelinx, 2005; Wickham, 2007; Wikipedia, 2019; Yli-Viikari et al., 2007; Zuur et al., 2009)

**Bibliography**
áâàäçéêëèíuîïìóôöòúûüù A. (2020). Title. Journal.
Achternaam (2020a). Title. Journal 1 (2): 3‑4.
Achternaam V. (2020b). Title. Journal 1: 3‑4.
Achternaam V. (2020c). Title. Journal 1: 3.
Achternaam V.T. (2020d). Title. Journal 1 (2): 3.
Achternaam V.T. (2020e). Title. Journal 1.
Achternaam V.T.D. (2020f). Title. Journal 1: 3.
Achternaam V.T.D. (2020g). Title. Journal 1 (2).
Agresti A. (2002). Categorical data analysis. John Wiley and Sons, Hoboken, New Jersey.
Amano T. (2012). Unravelling the dynamics of organisms in a changing world using ecological modelling. Ecological Research 27 (3): 495‑507. https://doi.org/10.1007/s11284-012-0928-6.
Anonymous (2020a). A manual title without author. 3e éd. A Series in Title Case, Vol. 12. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Anonymous (éd.) (2020b). A proceedings title without editor. A Series in Title Case, Vol. 12. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Anonymous (2020c). A single author booklet title. Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Anselin A., Devos K. & Vermeersch G. (2014). Blauwdruk vogels. In: De Knijf G., Westra T., Onkelinx T., Quataert P. & Pollet M. (éd.). Monitoring Natura 2000-soorten en overige soorten prioritair voor het Vlaams beleid, Rapporten van het Instituut voor Natuur- en Bosonderzoek 2011. Instituut voor Natuur- en Bosonderzoek, Brussels, Belgium, p. 188‑211.
Article A. (2020). A title. Journal of ALLCAPS and Title Case 123 (456): 7‑89. https://doi.org/10.1007/s11284-012-0928-6.
Article A. & Second A. (2020). A title. Journal of ALLCAPS and Title Case 123 (456): 7‑89. https://doi.org/10.1007/s11284-012-0928-6.
Article A., Second A. & Third A. (2020). A triple author article. Journal of ALLCAPS and Title Case 123 (456): 7‑89. https://doi.org/10.1007/s11284-012-0928-6.
Banerjee S., Carlin B.P. & Gelfand A.E. (2003). Hierarchical modeling and analysis for spatial data. Chapman and Hall, Boca Raton, Florida, USA.
Bolker B.M. (2008). Ecological models and data in r. Princeton University Press, Princeton, New Jersey, USA.
Book A. (2020a). A book with a single author. A title. 1re éd. ALLCAPS and Title Case Series, No 2. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Book A. & Second A. (2020a). A book with two authors. A title. 1st éd. ALLCAPS and Title Case Series, No 2. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Book A., Second A. & Third A. (2020a). A book with three authors. A title. 2e éd. ALLCAPS and Title Case Series, Vol. 1. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Book E. (éd.) (2020b). A book with a single editor. A title. 2e éd. ALLCAPS and Title Case Series, Vol. 1. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Book E. & Second E. (éd.) (2020b). A book with two editors. A title. 1re éd. ALLCAPS and Title Case Series, No 2. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Book E., Second E. & Third E. (éd.) (2020b). A book with a three editors. A title. 1re éd. ALLCAPS and Title Case Series, Vol. 1. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Booklet A. (2020). A single author booklet title. Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Booklet A. & Second A. (2020). A double author booklet title. Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Booklet A., Second A. & Third A. (2020). A triple author booklet title. Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Chapter A. (2020a). A single author techreport. 2e éd. Series in Title Case, Vol. 12. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow, p. 1‑2. https://doi.org/10.1007/s11284-012-0928-6.
Chapter A. (2020b). A single author and single editor PhD thesis title. 2e éd. Series in Title Case, No 34. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow, p. 123. https://doi.org/10.1007/s11284-012-0928-6.
Chapter A. & Second A. (2020). A two author software title. 2e éd. Series in Title Case, Vol. 12. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow, p. 1‑2. https://doi.org/10.1007/s11284-012-0928-6.
Chapter A., Second A. & Third A. (2020). A three author book title. 2e éd. Series in Title Case, No 34. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow, p. 1‑2. https://doi.org/10.1007/s11284-012-0928-6.
Chapter E. (éd.) (2020c). A single editor book. 2e éd. Series in Title Case, Vol. 12. ALLCAPS and Title Case Publishing, Somewhere over the Rainbow, p. 123. https://doi.org/10.1007/s11284-012-0928-6.
Conference A. (2020). A single author conference title. In: Conference E. (éd.). A single editor conference book title, A Series in Title Case, Vol. 12. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow, p. 56‑78. https://doi.org/10.1007/s11284-012-0928-6.
Conference A. & Second A. (2020). A double author conference title. In: Editor F.N. (éd.). A conference book without editor title, A Series in Title Case, No 34. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow, p. 56‑78. https://doi.org/10.1007/s11284-012-0928-6.
Conference A., Second A. & Third A. (2020). A triple author conference title. In: ConferenceEditor, Second E. & Third E. (éd.). A triple editor conference book title, A Series in Title Case, Vol. 12. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow, p. 56‑78. https://doi.org/10.1007/s11284-012-0928-6.
Databank Ondergrond Vlaanderen (s.d.). Bepalen gemiddelde grondwaterstand op een plaats. https://www.dov.vlaanderen.be/page/bepalen-gemiddelde-grondwaterstand-op-een-plaats (consulté le 24 juillet 2018).
De Achternaam V. (2020). Title. Journal 1 (2): 3.
Degraer S., Baeye M., Botteldooren D., Brabant R., Coates D., Courtens W., Debusschere E., Dekoninck L., De Maersschalck V., De Mesel I., Deschutter Y., Derweduwen J., Di Marcantonio M., Fettweis M., Francken F., Haelters J., Haerens P., Hostens K., Houthaeve R., Houziaux J.-S., Kerckhof F., Mathys M., Onkelinx T., Reubens J., Rumes B., Sas M., Stienen E., Vanaverbeke J., Vandendriessche S., Vanden Eede S., Van Den Eynde D., Van de walle M., Vanermen N., Van Hoey G., Vanhulle A., Van Lancker V., Van Renterghem T., Verstraete H., Vigin L. & Vinck M. (2013). Executive summary. In: Degraer S., Brabant R. & Rumes B. (éd.). Environmental impacts of offshore wind farms in the Belgian part of the North Sea. Royal Belgian Institute of Natural Sciences, Brussels, Belgium, p. 9‑13.
Diggle P.J. & Ribeiro P.J. (2007). Model-based geostatistics. Springer series in statistics. Springer, New York.
European Topic Centre on Biological Diversity ETC/BD (2016). Reference Portal for Natura 2000. http://bd.eionet.europa.eu/activities/Natura_2000/reference_portal (consulté le 31 mai 2016).
Franklin J. (2009). Mapping Species Distributions: Spatial Inference and Prediction. Cambridge University Press, Cambridge. http://www.alibris.com/Mapping-Species-Distributions-Spatial-Inference-and-Prediction-Janet-Franklin/book/12212704.
Import errors found: Unresolved @string reference « dataset » (s.d.). .
InCollection A. (2020). A single author part title. In: InCollection E. (éd.). The single editor book title, A Series in Title Case, No 23, 3e éd. Title Case and ALLCAPS, Somewhere over the rainbow, p. 12‑34. https://doi.org/10.1007/s11284-012-0928-6.
InCollection A. & Second A. (2020). A double author part title. In: The book without editor title, A Series in Title Case, Vol. 12, 3e éd. Title Case and ALLCAPS, Somewhere over the rainbow, p. 12‑34. https://doi.org/10.1007/s11284-012-0928-6.
InCollection A., Second A. & Third A. (2020). A double author part title. In: Collection E., Second E. & Third E. (éd.). The book without editor title, A Series in Title Case, No 23, 3e éd. Title Case and ALLCAPS, Somewhere over the rainbow, p. 12‑34. https://doi.org/10.1007/s11284-012-0928-6.
Kish L. (1965). Survey sampling. John Wiley & Sons, Ltd.
Laferrière E. & Stoett P.J. (1999). International relations theory and ecological thought: Towards a synthesis. Routledge.
Lastname F. (2020). Webpage title. In: Website title. https://example.com/titletest (consulté le 12 novembre 2020).
Manual A. (2020). A single author manual title. 3e éd. A Series in Title Case, No 34. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Manual A. & Second A. (2020). A double author manual title. 3e éd. A Series in Title Case, No 34. Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Manual A., Second A. & Third A. (2020). A triple author manual title. Vol. 12. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
MasterThesis A. (2020). The title of a master thesis. University of INBO, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Misc A. (2020). A single author misc title. https://doi.org/10.1007/s11284-012-0928-6.
Onkelinx T. (2009). Geostatistical analysis of the regeneration of Sycamore (Acer pseudoplatanus) in Flanders (Belgium). Ghent Univerisity, Faculty of Sciences.
Onkelinx T., Bauwens D. & Quataert P. (2012). Can we combine existing monitoring schemes for a new question or should we design a new dedicated monitoring scheme? A consideration based on statistical power and costs. In: Gonçalves A.M., Sousa I., Machado L., Pereira P., Menezes R. & Faria S. (éd.). METMA VI International Workshop on spatio-temporal modelling. 12-14 september 2012, Vol. 4. Guimarães, Portugal, p. 1‑22.
Onkelinx T., Devos K. & Quataert P. (2014a). Applying multiple imputation on waterbird census data. In: 4th International Statistical Ecology Conference. Montpellier, France, p. 35.
Onkelinx T., Gijselings R. & De Knijf G. (2014b). Blauwdruk vleermuizen. In: De Knijf G., Westra T., Onkelinx T., Quataert P. & Pollet M. (éd.). Monitoring Natura 2000-soorten en overige soorten prioritair voor het Vlaams beleid: Blauwdrukken soortenmonitoring in Vlaanderen, Rapporten van het Instituut voor Natuur- en Bos- onderzoek 2011. Instituut voor Natuur- en Bosonderzoek, p. 135‑169.
Onkelinx T., Westra T. & Vanderhaeghe F. (2019). GRTS master sample for habitat monitoring in Flanders. Zenodo. https://doi.org/10.5281/zenodo.2682323.
Oosterlynck P. (2019). Distribution of the Natura 2000 habitat type 7220 (Cratoneurion) in Flanders, Belgium (version 2019). Zenodo. https://doi.org/10.5281/zenodo.3550995.
PhDThesis A. (2020). The title of the PhD thesis. University of INBO, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Proceedings E. (éd.) (2020). A single editor proceedings title. A Series in Title Case, No 34. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Proceedings E. & Second E. (éd.) (2020). A double editor proceedings title. A Series in Title Case, Vol. 12. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Proceedings E., Second E. & Third E. (éd.) (2020). A double editor proceedings title. A Series in Title Case, No 34. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
ProceedingsAuthor A. (2020). A single author proceedings article title. In: A proceedings title, A Series in Title Case, Vol. 12. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow, p. 56‑78. https://doi.org/10.1007/s11284-012-0928-6.
ProceedingsAuthor A. & Second A. (2020). A double author proceedings article title. In: ProceedingsEditor A. (éd.). A single editor proceedings title, A Series in Title Case, No 34. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow, p. 56‑78. https://doi.org/10.1007/s11284-012-0928-6.
ProceedingsAuthor A., Second A. & Third A. (2020). A triple author proceedings article title. In: ProceedingsEditor A., Second E. & Third E. (éd.). A triple editor proceedings title, A Series in Title Case, Vol. 12. Title Case and ALLCAPS Publishing, Somewhere over the Rainbow, p. 56‑78. https://doi.org/10.1007/s11284-012-0928-6.
R Core Team (2013). R: A language and environment for statistical computing. Version 3.0.1. R Foundation for Statistical Computing, Vienna, Austria. http://www.r-project.org/.
TechnicalReport A. (2020). A single author technical report. No 123. Research Institute for Nature and Forest, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
TechnicalReport A. & Second A. (2020). A double author technical report without number. Research Institute for Nature and Forest, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
TechnicalReport A., Second A. & Third A. (2020). A double author technical report. No 123. Research Institute for Nature and Forest, Somewhere over the Rainbow. https://doi.org/10.1007/s11284-012-0928-6.
Unpublished A. (2020). A single author unpublished work. https://doi.org/10.1007/s11284-012-0928-6.
Unpublished A. & Second A. (2020). A double author unpublished work. https://doi.org/10.1007/s11284-012-0928-6.
Unpublished A., Second A. & Third A. (2020). A double author unpublished work. https://doi.org/10.1007/s11284-012-0928-6.
Van de Achternaam V. (2020). Title. Journal 1 (2): 3‑4.
Vander Mijnsbrugge K. & Onkelinx T. (2005). Samen in de bres voor inheemse bomen en struiken. Nieuwsbrief IBW-IN 8 (2): 1.
Wickham H. (2007). Reshaping data with the reshape package. Journal of Statistical Software 21 (12): 1‑20.
Wikipedia (2019). Muizenberg (Limburg). https://nl.wikipedia.org/w/index.php?title=Muizenberg_(Limburg)&oldid=53081088 (consulté le 30 juin 2020).
Yli-Viikari A., Hietala-Koivu R., Huusela-Veistola E., Hyvönen T., Perälä P. & Turtola E. (2007). Evaluating agri-environmental indicators (AEIs)—Use and limitations of international indicators at national level. Ecological Indicators 7 (1): 150‑163. https://doi.org/10.1016/j.ecolind.2005.11.005.
Zuur A.F., Ieno E.N., Walker N., Saveliev A.A. & Smith G.M. (2009). Mixed effects models and extensions in ecology with R. Springer New York, New York, NY. https://doi.org/10.1007/978-0-387-87458-6.

</details>

**Comment by ElsLommelen** [comment]
I checked the output, and the only thing I would change, is indeed removing the space in `s. d.` for consistency between languages.  But I'm not an expert in french citation styles (I only checked some journal articles), so I leave it up to @cecileherr to propose additional changes.

**Comment by cecileherr** [comment]
It is becoming quite a specialized discussion, I am afraid a native speaker's feeling will not be enough to give a definitive answer ;-) 

So for what it is worth:
French language tends to use more spaces than Dutch or English, so I wasn't even surprised to see `s.&#160;d.` (with a non breaking space thus) instead of `s.d.` in the [French version of the csl](https://github.com/citation-style-language/locales/blob/d5ee85de8e74d4109509014758b6f496a968ff03/locales-fr-FR.xml#L42). After a bit of research it seems both forms are used but apparently the version without a space seems to be more common (?). So ok for me to replace it by `s.d.`. In the French csl I only see one more candidate for a space removal: sub verbo (sing & plural), and again I can find both forms `s.v.` and `s.&#160;v.` in the literature (note that the other `&#160;` in the French csl - used with quotes - are definitely needed in French)

**Comment by cecileherr** [comment]
@florisvdh: regarding your question about changing the official csl for French: I am afraid I am not qualified to make really relevant suggestions (is there a librarian in the room? ;-) )

**Comment by florisvdh** [comment]
Thanks @cecileherr for shedding light on the use of spaces _en français_. I conclude:

- it is reasonable to leave the CSL locale file for fr-FR as-is, given that spaces are often used in French and we're not specialists in that. I leave it totally up to you whether or not to ask about it to the creators of the file, at https://github.com/citation-style-language/locales.
- since `s.d.` is often used without space as well, it is OK to keep this change in our style file. I'll move on with our CSL style file release, then.

**Comment by florisvdh** [comment]
Closed by citation-style-language#5634
